// Technology inventory from cv.md. Familiar tools stay in their own folder.
export type Technology = { name: string; icon?: string; monogram?: string };

export const techStack: Technology[] = [
  { name: "Node.js", icon: "nodedotjs" },
  { name: "React", icon: "react" },
  { name: "TypeScript", icon: "typescript" },
  { name: "JavaScript", icon: "javascript" },
  { name: "Python", icon: "python" },
  { name: "Java", monogram: "J" },
  { name: "PHP", icon: "php" },
  { name: "SQL", monogram: "SQL" },
  { name: "Express.js", icon: "express" },
  { name: "Django", icon: "django" },
  { name: "Flask", icon: "flask" },
  { name: "HTML", icon: "html5" },
  { name: "CSS", icon: "css" },
  { name: "PostgreSQL", icon: "postgresql" },
  { name: "MySQL", icon: "mysql" },
  { name: "MongoDB", icon: "mongodb" },
  { name: "Firestore", icon: "firebase" },
  { name: "Google Cloud", icon: "googlecloud" },
  { name: "Cloud Run", icon: "googlecloud" },
  { name: "Pub/Sub", icon: "googlecloud" },
  { name: "Cloud Tasks", icon: "googlecloud" },
  { name: "AWS · EC2 / S3", monogram: "AWS" },
  { name: "Docker", icon: "docker" },
  { name: "VMware", icon: "vmware" },
  { name: "Parallels", monogram: "VM" },
  { name: "Firebase", icon: "firebase" },
  { name: "Linux", icon: "linux" },
  { name: "Nginx", icon: "nginx" },
  { name: "OAuth 2.0", monogram: "AUTH" },
  { name: "OpenID Connect", icon: "openid" },
  { name: "JWT", icon: "jsonwebtokens" },
  { name: "Mocha", icon: "mocha" },
  { name: "Vitest", icon: "vitest" },
  { name: "Git", icon: "git" },
  { name: "Groq API", monogram: "G" },
  { name: "Claude", icon: "claude" },
  { name: "Cursor", icon: "cursor" },
  { name: "GitHub Copilot", icon: "githubcopilot" },
];

export const familiarStack: Technology[] = [
  { name: "Kafka", icon: "apachekafka" },
  { name: "Redis", icon: "redis" },
  { name: "Spring Boot", icon: "springboot" },
  { name: "JPA", monogram: "JPA" },
  { name: "Hibernate", icon: "hibernate" },
  { name: "Tailwind CSS", icon: "tailwindcss" },
];
